### ISSUE TITLE
e-plus table in 1.7.10 does not accept "End Forged" weapons and tools from calculator mod

### ISSUE THREAD

**Issue by iLLHunter** [xkyouchoux/EnchantingPlus#1]
End-forged tools and sword, from the calculator mod, are enchantable in vanilla table and in anvil with books. The e-plus table does not accept them for enchanting however

**Comment by xkyouchoux** [comment]
I'm sorry to disappoint you, but I no longer work on this project. Please redirect any issues to the current thread @ http://www.minecraftforum.net/forums/mapping-and-
modding/minecraft-mods/1286469-enchanting-plus thank you.

**Comment by xkyouchoux** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286469-enchanting-plus
